### ISSUE TITLE
before release todo list

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/amtrex#1]
- [x] handle duplication issue by filtering in automo
- [x] fix CSV download 
- [x] a nicer extension popup 
- [ ] improve the "compare" experience

**Comment by vecna** [comment]
- [ ] ignore the 'total' in client pagination, or handle that hack somehow.

**Comment by vecna** [comment]
- [x] fix the parsing and guarantee a robust link between products and categories

**Comment by vecna** [comment]
- [ ] add developer privilege to download all the product CSV
